{
 "title": "IPMap",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "# Used memory\nnode_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Total memory\nnode_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Addresses Located",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(latitude, longitude, country, city, ip_address, timestamp) (max_over_time(nginx_geoip_location_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}