name: Deploy Monitoring
on:
  push:
    branches: [main]

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Check if should run
        if: ${{ !contains(github.event.head_commit.message, 'monitoring_deploy') && !contains(github.event.head_commit.message, 'all_deploy') }}
        run: exit 78
      - name: Manually clone DevOps repository
        env:
          GITHUB_PAT: ${{ secrets.GITHUB }}
        run: |
          git config --global url."https://api:${GITHUB_PAT}@github.com/".insteadOf "https://github.com/"
          git clone --depth 1 https://github.com/PaulElser/DevOps.git devops

      - name: Deploy monitoring services
        working-directory: devops/monitoring
        run: |
          docker compose down
          docker compose up -d
